POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_HOST=localhost
POSTGRES_HOST=5432
POSTGRES_DB=main


DATABASE_CONNECTION_URI = f'postgresql+psycopg2://{POSTGRES_USER}:{SPOSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_HOST}/{POSTGRES_DB}'