version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8002:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes: 
      - /var/lib/postgresql/postgres
