version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports: 
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  
  queue:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    ports:
      - '5433:5432'
    volumes: 
      - /var/lib/postgresql/postgres
